### ISSUE TITLE
WebSocket error code

### ISSUE THREAD

**Issue by sky-L** [abi/screenshot-to-code#66]
"Your demonstration website has the same error, please take a look."

**Comment by sky-L** [comment]
also docker-composer  is the same  error

**Comment by abi** [comment]
Can you post screenshots of your docker logs?

**Comment by 18984955240** [comment]
<img width="609" alt="WeChat03848ea817c985ddf6211a5fb2a83b94" src="https://github.com/abi/screenshot-to-code/assets/16495539/4dc4e1c6-a458-41fe-b185-3357dd6b25c6">

**Comment by 18984955240** [comment]
i have same trouble like him

**Comment by Selenium39** [comment]
```
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_WS_BACKEND_URL: ws://${YOUR SERVER IP}:7001
    ports:
      - "5173:5173"
```


add `VITE_WS_BACKEND_URL` in docker-compose.yml can resolve this error
