### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by davask** [abi/screenshot-to-code#83]
Hi, I tried the [online version](https://picoapps.xyz/free-tools/screenshot-to-code) of your tool with my API key but I got an error from that following screenshot 

![Web capture_22-11-2023_22822_www maras-it com](https://github.com/abi/screenshot-to-code/assets/482210/3c331d2e-cd22-4d65-8d4d-003468cd0c2e)

which return this in the console :

```JS
WebSocket error code CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecode: 1006composed: falsecurrentTarget: WebSocket {url: 'wss://backend-screenshot-to-code.onrender.com/generate-code', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}defaultPrevented: falseeventPhase: 0reason: ""returnValue: truesrcElement: WebSocket {url: 'wss://backend-screenshot-to-code.onrender.com/generate-code', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}target: WebSocket {url: 'wss://backend-screenshot-to-code.onrender.com/generate-code', readyState: 3, bufferedAmount: 0, onopen: null, onerror: null, …}timeStamp: 70399.80000001192type: "close"wasClean: false[[Prototype]]: CloseEventcode: (...)reason: (...)wasClean: (...)constructor: ƒ CloseEvent()Symbol(Symbol.toStringTag): "CloseEvent"bubbles: (...)cancelBubble: (...)cancelable: (...)composed: (...)currentTarget: (...)defaultPrevented: (...)eventPhase: (...)returnValue: (...)srcElement: (...)target: (...)timeStamp: (...)type: (...)get code: ƒ code()get reason: ƒ reason()get wasClean: ƒ wasClean()[[Prototype]]: Event
(anonymous) @ index-9af3e78e.js:225
```

<img width="946" alt="image" src="https://github.com/abi/screenshot-to-code/assets/482210/b8403fbe-fc6b-479d-92ea-5f70610b3d6c">

any idea on that topic ?

david

**Comment by JoshuaYang2001** [comment]
same question, Connection closed 1006

**Comment by zhengdechang** [comment]
add VITE_WS_BACKEND_URL env, using the ip of your host, here is my example

```
version: '3.3'
  
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - .env

    # or 
    # environment:
      #- BACKEND_PORT=7001   # if you change the port, make sure to also change the VITE_WS_BACKEND_URL at frontend/.env.local
      # - OPENAI_API_KEY=your_openai_api_key

    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"

    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_BACKEND_URL=ws://192.168.17.24:7001
```
