### ISSUE TITLE
WebSocket Error: Connection Closed 1006 - this worked for me

### ISSUE THREAD

**Issue by SystemExecuteLLC** [abi/screenshot-to-code#87]
If you're getting this:
![image](https://github.com/abi/screenshot-to-code/assets/108966041/3003b958-6bec-4bf1-9ac4-882421a14407)

Try running the backend with 7001 instead of 7000:

`poetry run uvicorn main:app --reload --port 7001`

**Comment by abi** [comment]
Thanks! We made the mistake of changing the port after the initial release. 

When did you first clone the repo?

**Comment by zhengdechang** [comment]
add VITE_WS_BACKEND_URL env, using the ip of your host, here is my example

```
version: '3.3'
  
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - .env

    # or 
    # environment:
      #- BACKEND_PORT=7001   # if you change the port, make sure to also change the VITE_WS_BACKEND_URL at frontend/.env.local
      # - OPENAI_API_KEY=your_openai_api_key

    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"

    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_BACKEND_URL=ws://192.168.17.24:7001
```
