### ISSUE TITLE
WebSocket Error: Connection Closed 1007

### ISSUE THREAD

**Issue by 3dkrender** [abi/screenshot-to-code#89]
Playing with Docker. When trying to upload an image it drop this error.

![image](https://github.com/abi/screenshot-to-code/assets/51716993/97f1954d-7ee7-45f8-b4a2-49d9986541d5)

**Comment by zhengdechang** [comment]
add VITE_WS_BACKEND_URL env, using the ip of your host, here is my example

```
version: '3.3'
  
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - .env

    # or 
    # environment:
      #- BACKEND_PORT=7001   # if you change the port, make sure to also change the VITE_WS_BACKEND_URL at frontend/.env.local
      # - OPENAI_API_KEY=your_openai_api_key

    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"

    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_WS_BACKEND_URL=ws://192.168.17.24:7001
```
